# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: dw/VdCR2KFMlvYOLqa8Zy23hAgFg7m4fr1eknksX/feGkXbTB4JZHInwF3gTDK3baKJ/E1HdvXUfQksS5JzTc44NLd5dmNqOQE41R9TZqWV5i4sTHXcW4qv8XyTZ28ynOMXiAHhMmWzr02INdQeQNBGey9Y8TQZA3DoHKArd0Bzmvy6+yMLJTMP36bJ5gKYhVD/0Igu5AwBoGSzBalBRU5IogS5T8yuPgoZ3IQUlHdom3659U4lnQEtd9LK+KI4sStPS9Mg5RDTMub4BgKfrBxAXEWhYG3L+4ezk3M/1ld/uKqHo0H/6NHe7dLoVRNHktyJMwRc15TuyR9P8SWHOwPn7y4AEMs7uj5Hyj5goe2NLHGuUSnmjz6m8mMtg6H07FrPSrnb+8ehTxBraJiwP6xvqT3Vchpfxbkl5HUDn8zS8EJH8xQaIzPe0fbs6YbwyhQ42jJnfPHiYnMvos3EcdpACQcwaa9GBC97vNuJabNcETHDWrsPe1Ue+jeb465gjRRRbJC/vrvp6aFbeJL0qRN4Ph9dXCy3jBYi+Ja4+r87Fx0zXliwhWuKu3mPcEDEVvTh+Wx92bFyBwgMpRTqdyqF3Cg2mf064f5oEcnEcrixfH/u8IjMVmOFtcHBf0jpW3J5/q5k6hIAukgb5UMH8H6nOtwqHwJs1NXdzu/tzBIQ=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-osv
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: dw/VdCR2KFMlvYOLqa8Zy23hAgFg7m4fr1eknksX/feGkXbTB4JZHInwF3gTDK3baKJ/E1HdvXUfQksS5JzTc44NLd5dmNqOQE41R9TZqWV5i4sTHXcW4qv8XyTZ28ynOMXiAHhMmWzr02INdQeQNBGey9Y8TQZA3DoHKArd0Bzmvy6+yMLJTMP36bJ5gKYhVD/0Igu5AwBoGSzBalBRU5IogS5T8yuPgoZ3IQUlHdom3659U4lnQEtd9LK+KI4sStPS9Mg5RDTMub4BgKfrBxAXEWhYG3L+4ezk3M/1ld/uKqHo0H/6NHe7dLoVRNHktyJMwRc15TuyR9P8SWHOwPn7y4AEMs7uj5Hyj5goe2NLHGuUSnmjz6m8mMtg6H07FrPSrnb+8ehTxBraJiwP6xvqT3Vchpfxbkl5HUDn8zS8EJH8xQaIzPe0fbs6YbwyhQ42jJnfPHiYnMvos3EcdpACQcwaa9GBC97vNuJabNcETHDWrsPe1Ue+jeb465gjRRRbJC/vrvp6aFbeJL0qRN4Ph9dXCy3jBYi+Ja4+r87Fx0zXliwhWuKu3mPcEDEVvTh+Wx92bFyBwgMpRTqdyqF3Cg2mf064f5oEcnEcrixfH/u8IjMVmOFtcHBf0jpW3J5/q5k6hIAukgb5UMH8H6nOtwqHwJs1NXdzu/tzBIQ=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-osv
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: emeZjJV64D1jvB/ij53kIhe7Bub/teDttmi/MZ/u8XeeyDOfUFtWeAOGyw766dbnyYOYaa42Gs/CxyZomkfyFxEWIK39HJDmhaRFCdsOww/Oj58DFzNZRVWggnhdGi8PTBTfQwL2LK8AobPwPg02v/RB2zRShbPXP20wMHI273AFO9QcndP1dLG6dDABsx2OGDMc1dTYFUhYTMx/tXqiINFxTvc42UpK63XRTf6O0idKxIqWwpuSKzP+FKwdna2phCZ/Ml+Cr5lG/o0W0pwtbT1Of8CLXraYqaVMltSe3ZF9a7PFyDCHzpYAeOQM8Lo9rayd7ZQ0jrfkytu6yBCcnwdElkfZ5WpShCKWUf7KAMPGQrAEob8MWGQgYIqP+jWPSC2ouqdS0EZLjmOBhAuDdz/HdIRXK0p6cU7kK62RhmDA9O3RR0O80v+9GzK+SZTmsMlGRstCwF0ctNICmzYOpz61NbbpATBttmn2dT7ovYg1XPP0aUDk+fB00F5axro4a6NpKhoxXVs0aUfBC98r3QqGjDzGVjRytOQMew9dag7DFud9yb3Mdgyu+sTkx0UqZ8dROKG6+lF8Ro6aBiST8eNDQigHb0mx99FXO7HhW9CQVmN3WxBpg2ptIqRCzyspNPHBEFHfOX+ku+qE9gnItTPMEUarSeFSsQTru79eDGs=
  file:
    - release/snap-plugin-collector-osv_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-osv
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
